---
- name: Include variables specific for the distribution.
  ansible.builtin.include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

- name: Include install tasks.
  ansible.builtin.include_tasks:
    file: install.yml
- name: Include configure tasks.
  ansible.builtin.include_tasks:
    file: configure.yml
